language: python

# sudo false implies containerized builds, so we can use cacheing
sudo: false

notifications:
  email: false

python:
  - 3.6

env:
  - CONDA_DEPS="pip flake8 pytest coverage pandas xarray dask" PIP_DEPS="codecov pytest-cov"

before_install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget http://repo.continuum.io/miniconda/Miniconda-3.16.0-Linux-x86_64.sh -O miniconda.sh;
    else
      wget http://repo.continuum.io/miniconda/Miniconda3-3.16.0-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -f -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION $CONDA_DEPS
  - source activate test-environment
  - travis_retry pip install $PIP_DEPS

install:
- python setup.py install --record installed_files.txt

script:
- py.test xbatcher --cov=xrft --cov-config .coveragerc --cov-report term-missing -v

after_success:
- codecov
